mail.host=sandbox.smtp.mailtrap.io
mail.port=2525
mail.username=92459510f5f0ce
mail.password=1be5609c705795
app.mail=hello.aesthetica@gmail.com
app.name=aesthetica
app.url=http://localhost:8080/aesthetica
# PayHere merchant credentials (used by PayHereUtil).
payhere.merchant.id=1224621
payhere.merchant.secret=MjgxNzA1MDMzMTk3NzczNDYzMzMyODc4MjcxODUyMjkwNDE2Nzgz
